Repository peer-42seoul/Peer-Backend, pull requests merged in 2023-11, with the labels that each got.

#235 [REFACTOR]Profile module apply file module
  backend/src/main/java/peer/backend/service/profile/ProfileService.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-prod.yml
  backend/src/test/java/peer/backend/profile/ProfileServiceTest.java
Labels: refactor

#234 [REFACOTR] signup dto 유효성 검증 추가 #288
  backend/src/main/java/peer/backend/dto/security/UserInfo.java
  backend/src/main/java/peer/backend/entity/user/User.java
  backend/src/main/java/peer/backend/exception/GlobalControllerAdvice.java
  backend/src/test/java/peer/backend/keyword/UserPushKeywordRepositoryTest.java
  backend/src/test/java/peer/backend/team/InterestedProjectRepositoryTest.java
  backend/src/test/java/peer/backend/team/TeamUserRepositoryTest.java
Labels: refactor

#227 FIX : remove param userId
  backend/src/main/java/peer/backend/controller/message/MessaageController.java
  backend/src/main/java/peer/backend/dto/message/TargetDTO.java
Labels: enhancement

#244 [REFACTOR] 242 feat api modification for response send message
  backend/src/main/java/peer/backend/controller/message/MessaageController.java
  backend/src/main/java/peer/backend/service/message/MessageMainService.java
Labels: enhancement

#255 [HOTFIX] 프로필 조회 API의 DTO 변경
  backend/src/main/java/peer/backend/dto/profile/response/MyProfileResponse.java
  backend/src/main/java/peer/backend/service/profile/ProfileService.java
  backend/src/test/java/peer/backend/profile/ProfileServiceTest.java
Labels: bug

#245 [REFACTOR] Haryu specific validation update
  backend/src/main/java/peer/backend/controller/message/MessaageController.java
  backend/src/main/java/peer/backend/dto/message/KeywordDTO.java
  backend/src/main/java/peer/backend/dto/message/MsgContentDTO.java
  backend/src/main/java/peer/backend/repository/user/UserRepository.java
Labels: bug, enhancement

#260 [FEAETURE] 비밀번호 임시발급 기능 개발 #236
  backend/src/main/java/peer/backend/controller/SignInController.java
  backend/src/main/java/peer/backend/controller/SignUpController.java
  backend/src/main/java/peer/backend/service/EmailAuthService.java
  backend/src/main/java/peer/backend/service/MemberService.java
Labels: enhancement

#270 [FIX] ouath google redirect url 추가
  backend/src/main/resources/application-dev.yml
Labels: bug

#269 [FIX] oauth redirect url 수정
  backend/src/main/java/peer/backend/oauth/OAuthAuthenticationSuccessHandler.java
Labels: bug

#277 [FIX] google oauth redirect url
  backend/src/main/resources/application-dev.yml
Labels: bug

#288 fix: get other profile not token
  backend/src/main/java/peer/backend/config/SecurityConfig.java
  backend/src/main/java/peer/backend/controller/profile/ProfileController.java
Labels: refactor

#293 fix: change Http error code and add password validation
  backend/src/main/java/peer/backend/controller/profile/PersonalInfoController.java
  backend/src/main/java/peer/backend/dto/profile/request/PasswordRequest.java
  backend/src/main/java/peer/backend/service/profile/PersonalInfoService.java
Labels: refactor

#283 279 hotfix alarmkeyword delete
  backend/src/main/java/peer/backend/controller/profile/KeywordAlarmController.java
  backend/src/main/java/peer/backend/service/profile/KeywordAlarmService.java
Labels: bug

#284 [FIX] withdrawal password verification
  backend/src/main/java/peer/backend/controller/SignUpController.java
Labels: bug

#272 258 hotfix profile controller and dto
  backend/src/main/java/peer/backend/controller/profile/ProfileController.java
  backend/src/main/java/peer/backend/dto/profile/request/EditProfileRequest.java
  backend/src/main/java/peer/backend/service/profile/ProfileService.java
  backend/src/test/java/peer/backend/profile/ProfileServiceTest.java
Labels: bug

#306 [FIX] refresh token 쿼리스트링에서 제거하고 쿠키에 추가
  backend/src/main/java/peer/backend/controller/SignInController.java
  backend/src/main/java/peer/backend/oauth/OAuthAuthenticationSuccessHandler.java
Labels: bug

#301 [HOTFIX] self searching issue
  .github/workflows/random_reviewers.yml
  backend/src/main/java/peer/backend/controller/message/MessaageController.java
  backend/src/main/java/peer/backend/service/message/MessageMainService.java
Labels: enhancement

#302 [HOTFIX] make a method to recovery message index deleted
  backend/src/main/java/peer/backend/service/message/MessageSubService.java
Labels: enhancement

#303 [HOTFIX] deleted message recovery strategy block deleted case
  backend/src/main/java/peer/backend/controller/message/MessaageController.java
  backend/src/main/java/peer/backend/exception/AlreadyDeletedException.java
  backend/src/main/java/peer/backend/service/message/MessageMainService.java
  backend/src/main/java/peer/backend/service/message/MessageSubService.java
Labels: bug

#304 [HOTFIX] message DTO, it needs refactoring
  backend/src/main/java/peer/backend/controller/message/MessaageController.java
  backend/src/main/java/peer/backend/dto/message/TargetDTO.java
  backend/src/main/java/peer/backend/dto/message/TargetForDelete.java
  backend/src/main/java/peer/backend/service/message/MessageMainService.java
Labels: enhancement

#310 [FIX] reissue use cookie
  backend/src/main/java/peer/backend/controller/SignInController.java
Labels: bug

#314 [FIX] wrong password throw 403
  backend/src/main/java/peer/backend/controller/SignUpController.java
  backend/src/main/java/peer/backend/service/MemberService.java
Labels: bug

#319 [FEATURE] 유저 탈퇴 추적
  backend/src/main/java/peer/backend/annotation/tracking/UserWithdrawalTracking.java
  backend/src/main/java/peer/backend/aspect/UserTrackingAspect.java
  backend/src/main/java/peer/backend/mongo/entity/enums/UserTrackingStatus.java
  backend/src/main/java/peer/backend/service/ExcelService.java
  backend/src/main/java/peer/backend/service/MemberService.java
Labels: enhancement

#320 273 bug first message failed
  backend/src/main/java/peer/backend/controller/message/MessaageController.java
  backend/src/main/java/peer/backend/service/message/MessageMainService.java
  backend/src/main/java/peer/backend/service/message/MessageSubService.java
Labels: bug

#323 [FEATURE] Team Create Tracking
  backend/src/main/java/peer/backend/annotation/tracking/TeamCreateTracking.java
  backend/src/main/java/peer/backend/aspect/TeamTrackingAspect.java
  backend/src/main/java/peer/backend/mongo/entity/TeamTracking.java
  backend/src/main/java/peer/backend/mongo/repository/TeamTrackingRepository.java
  backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
  backend/src/main/java/peer/backend/service/team/TeamService.java
Labels: enhancement

#335 [FEATURE] TeamTracking Excel Download
  backend/src/main/java/peer/backend/mongo/entity/TeamTracking.java
  backend/src/main/java/peer/backend/service/ExcelService.java
Labels: enhancement

#352 [FIX] oauth redirect url modified
  backend/src/main/java/peer/backend/oauth/OAuthAuthenticationSuccessHandler.java
Labels: enhancement

#371 [FIX] refresh cookie add path
  backend/src/main/java/peer/backend/controller/SignInController.java
  backend/src/main/java/peer/backend/oauth/OAuthAuthenticationSuccessHandler.java
Labels: bug

#369 FEAT: Add new error handling logic
  backend/src/main/java/peer/backend/controller/message/MessaageController.java
  backend/src/main/java/peer/backend/service/message/MessageMainService.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-prod.yml
Labels: enhancement

#367 FEAT: update conversationList api
  backend/src/main/java/peer/backend/controller/socket/SocketIoServerController.java
  backend/src/main/java/peer/backend/dto/message/MsgTarget.java
  backend/src/main/java/peer/backend/service/message/MessageMainService.java
  backend/src/main/java/peer/backend/service/message/MessageSubService.java
Labels: enhancement

#368 [FEATURE] Team Update Tracking
  backend/src/main/java/peer/backend/annotation/tracking/TeamUpdateTracking.java
  backend/src/main/java/peer/backend/aspect/TeamTrackingAspect.java
  backend/src/main/java/peer/backend/mongo/repository/TeamTrackingRepository.java
  backend/src/main/java/peer/backend/service/team/TeamService.java
Labels: enhancement

#372 [FEAT] User Registration Activty Tracking
  backend/src/main/java/peer/backend/aspect/ActivityTrackingAspect.java
  backend/src/main/java/peer/backend/mongo/ActivityTrackingListener.java
  backend/src/main/java/peer/backend/mongo/SequenceGeneratorService.java
  backend/src/main/java/peer/backend/mongo/entity/ActivityTracking.java
  backend/src/main/java/peer/backend/mongo/entity/AutoIncrementSequence.java
  backend/src/main/java/peer/backend/mongo/entity/enums/ActionType.java
  backend/src/main/java/peer/backend/mongo/repository/ActivityTrackingRepository.java
Labels: enhancement

#375 353 feat message enhancement new logic for deleted message
  backend/src/main/java/peer/backend/controller/message/MessaageController.java
  backend/src/main/java/peer/backend/service/message/MessageMainService.java
  backend/src/main/java/peer/backend/service/message/MessageSubService.java
Labels: enhancement

#376 353 feat message enhancement add reverse message listlogic
  backend/src/main/java/peer/backend/service/message/MessageMainService.java
  backend/src/main/java/peer/backend/service/message/MessageSubService.java
Labels: enhancement

#378 FEAT: primitive socket controller and service finished
  backend/src/main/java/peer/backend/config/jwt/TokenProvider.java
  backend/src/main/java/peer/backend/controller/socket/SocketIoServerController.java
  backend/src/main/java/peer/backend/dto/socket/tempDTO.java
  backend/src/main/java/peer/backend/service/socket/SocketServerService.java
Labels: enhancement

#374 370 2step dnd dto
  backend/build.gradle
  backend/src/main/java/peer/backend/controller/temp/TempDnDController.java
  backend/src/main/java/peer/backend/dto/temp/RequestDnDDTO.java
  backend/src/main/java/peer/backend/entity/team/DataGrid.java
  backend/src/main/java/peer/backend/entity/team/Widget.java
  backend/src/main/java/peer/backend/mongo/entity/TeamDnD.java
  backend/src/main/java/peer/backend/mongo/repository/PeerLogDnDRepository.java
  backend/src/main/java/peer/backend/mongo/repository/TeamDnDRepository.java
  backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
  backend/src/main/java/peer/backend/service/temp/TempDnDService.java
Labels: enhancement

#382 HOTFIX: fix error handling HTTP status number
  backend/src/main/java/peer/backend/controller/message/MessaageController.java
  backend/src/main/java/peer/backend/service/message/MessageMainService.java
Labels: enhancement

#384 TEST: add testing repository and testing
  backend/src/main/java/peer/backend/entity/temp/Temp.java
  backend/src/main/java/peer/backend/repository/temp/TempRepository.java
Labels: enhancement

#385 ADD remote settings for socket
  backend/src/main/resources/application-dev.yml
Labels: enhancement

#383 [REFACTOR] user registration tracking refactoring
  backend/src/main/java/peer/backend/aspect/ActivityTrackingAspect.java
  backend/src/main/java/peer/backend/aspect/UserTrackingAspect.java
  backend/src/main/java/peer/backend/entity/user/User.java
  backend/src/main/java/peer/backend/service/MemberService.java
  backend/src/main/java/peer/backend/service/SocialLoginService.java
  backend/src/main/java/peer/backend/service/UserService.java
Labels: refactor

#404 [HOTFIX]: changeImage And OriginalImage same
  backend/src/main/java/peer/backend/service/team/TeamService.java
Labels: bug

#409 407 hotfix personal auth
  backend/src/main/java/peer/backend/dto/profile/response/PersonalInfoResponse.java
  backend/src/main/java/peer/backend/repository/user/SocialLoginRepository.java
  backend/src/main/java/peer/backend/service/profile/PersonalInfoService.java
  backend/src/test/java/peer/backend/profile/PersonalInfoServiceTest.java
Labels: refactor

#436 [HOTFIX] message LocalDateTime
  backend/src/main/java/peer/backend/controller/message/MessaageController.java
  backend/src/main/java/peer/backend/service/message/MessageSubService.java
Labels: enhancement
