Repository peer-42seoul/Peer-Backend, pull requests merged in 2023-12, with the labels that each got.

#442 [FIX] OAuth 예외 상황 처리
  backend/src/main/java/peer/backend/controller/SignUpController.java
  backend/src/main/java/peer/backend/oauth/PrincipalOauth2UserService.java
  backend/src/main/java/peer/backend/service/EmailAuthService.java
  backend/src/main/java/peer/backend/service/MemberService.java
  backend/src/main/java/peer/backend/service/SocialLoginService.java
  backend/src/main/java/peer/backend/service/profile/PersonalInfoService.java
  backend/src/test/java/peer/backend/profile/PersonalInfoServiceTest.java
Labels: bug

#461 [FIX] XSSFWorkbook close
  src/main/java/peer/backend/service/ExcelService.java
Labels: bug

#463 [FIX] secure cookie
  src/main/java/peer/backend/oauth/OAuthAuthenticationSuccessHandler.java
Labels: bug

#462 [FIX] secure cookie
  src/main/java/peer/backend/controller/SignInController.java
Labels: bug

#487 448 bug teaminforesponse
  src/main/java/peer/backend/dto/team/TeamInfoResponse.java
Labels: bug

#485 446 bug message controller
  src/main/java/peer/backend/controller/message/MessaageController.java
Labels: bug

#490 [FEATURE] Admin Login
  src/main/java/peer/backend/config/jwt/TokenProvider.java
  src/main/java/peer/backend/controller/SignInController.java
  src/main/java/peer/backend/dto/security/request/AdminLoginRequest.java
  src/main/java/peer/backend/entity/user/Admin.java
  src/main/java/peer/backend/entity/user/Login.java
  src/main/java/peer/backend/entity/user/User.java
  src/main/java/peer/backend/oauth/PrincipalDetails.java
  src/main/java/peer/backend/oauth/PrincipalOauth2UserService.java
  src/main/java/peer/backend/repository/user/AdminRepository.java
  src/main/java/peer/backend/service/AdminService.java
  src/main/java/peer/backend/service/LoginService.java
Labels: enhancement

#486 [REAFCTOR] recruit의 Tag를 admin의 tag를 사용하도록 리팩토링
  src/main/java/peer/backend/controller/TagController.java
  src/main/java/peer/backend/controller/board/RecruitController.java
  src/main/java/peer/backend/dto/board/recruit/RecruitCreateRequest.java
  src/main/java/peer/backend/dto/board/recruit/RecruitListResponse.java
  src/main/java/peer/backend/dto/board/recruit/RecruitResponce.java
  src/main/java/peer/backend/dto/board/recruit/RecruitUpdateRequestDTO.java
  src/main/java/peer/backend/dto/board/recruit/RecruitUpdateResponse.java
  src/main/java/peer/backend/dto/board/team/ShowcaseListResponse.java
  src/main/java/peer/backend/dto/tag/TagResponse.java
  src/main/java/peer/backend/entity/board/recruit/Recruit.java
  src/main/java/peer/backend/entity/composite/RecruitTagPK.java
  src/main/java/peer/backend/entity/tag/RecruitTag.java
  src/main/java/peer/backend/entity/tag/Tag.java
  src/main/java/peer/backend/repository/TagRepository.java
  src/main/java/peer/backend/service/TagService.java
  src/main/java/peer/backend/service/board/recruit/RecruitService.java
  src/main/java/peer/backend/service/board/team/ShowcaseService.java
  src/main/java/peer/backend/service/profile/FavoriteService.java
  src/test/java/peer/backend/board/ShowcaseServiceTest.java
Labels: refactor

#493 [FIX] 태그 삭제할때 에러, 어드민 권한 검사 수정하였습니다.
  src/main/java/peer/backend/entity/board/recruit/Recruit.java
  src/main/java/peer/backend/entity/tag/RecruitTag.java
  src/main/java/peer/backend/oauth/PrincipalDetails.java
  src/main/java/peer/backend/repository/board/recruit/RecruitRepository.java
  src/main/java/peer/backend/repository/board/recruit/RecruitTagRepository.java
  src/main/java/peer/backend/service/TagService.java
  src/main/java/peer/backend/service/UserDetailsServiceImpl.java
  src/main/java/peer/backend/service/board/recruit/RecruitService.java
Labels: bug

#491 DELETE old file service, old file controller
  src/main/java/peer/backend/controller/File/FileController.java
  src/main/java/peer/backend/service/file/FileService.java
  src/main/java/peer/backend/service/file/ObjectService.java
  src/test/java/peer/backend/profile/ProfileServiceTest.java
  src/test/java/peer/backend/service/ObjectServiceTest.java
Labels: bug

#492 DELETE: ProfileImageController_old
  src/main/java/peer/backend/controller/File/ProfileImageController_old.java
Labels: enhancement

#496 [FEATURE] 어드민 신고 관련 API 개발
  src/main/java/peer/backend/config/SecurityConfig.java
  src/main/java/peer/backend/controller/ReportController.java
  src/main/java/peer/backend/converter/ReportProcessingStatusConverter.java
  src/main/java/peer/backend/converter/ReportStatusConverter.java
  src/main/java/peer/backend/converter/ReportTypeConverter.java
  src/main/java/peer/backend/dto/report/ReportProcessingRequest.java
  src/main/java/peer/backend/dto/report/ReportRequest.java
  src/main/java/peer/backend/dto/report/ReportResponse.java
  src/main/java/peer/backend/entity/report/Report.java
  src/main/java/peer/backend/entity/report/ReportProcessingStatus.java
  src/main/java/peer/backend/entity/report/ReportStatus.java
  src/main/java/peer/backend/entity/report/ReportType.java
  src/main/java/peer/backend/repository/report/ReportRepository.java
  src/main/java/peer/backend/service/report/ReportService.java
Labels: enhancement

#497 [FEATURE] blacklist entity & 신고 처리(영구밴)
  src/main/java/peer/backend/controller/ReportController.java
  src/main/java/peer/backend/converter/BacklistTypeConverter.java
  src/main/java/peer/backend/converter/ReportProcessingStatusConverter.java
  src/main/java/peer/backend/dto/report/ReportProcessingRequest.java
  src/main/java/peer/backend/entity/blacklist/Blacklist.java
  src/main/java/peer/backend/entity/blacklist/BlacklistType.java
  src/main/java/peer/backend/entity/report/ReportProcessingType.java
  src/main/java/peer/backend/repository/blacklist/BlacklistRepository.java
  src/main/java/peer/backend/repository/report/ReportRepository.java
  src/main/java/peer/backend/service/blacklist/BlacklistService.java
  src/main/java/peer/backend/service/report/ReportService.java
Labels: enhancement

#505 [REFACTOR] 사용자 행동 DB화 리팩토링
  src/main/java/peer/backend/aspect/ActionTrackingAspect.java
  src/main/java/peer/backend/batch/JobConfig.java
  src/main/java/peer/backend/converter/ActionTypeEnumConverter.java
  src/main/java/peer/backend/entity/action/ActionType.java
  src/main/java/peer/backend/entity/action/Wallet.java
  src/main/java/peer/backend/mongo/ActionTrackingListener.java
  src/main/java/peer/backend/mongo/entity/ActionTracking.java
  src/main/java/peer/backend/mongo/entity/enums/ActionType.java
  src/main/java/peer/backend/mongo/entity/enums/ActionTypeEnum.java
  src/main/java/peer/backend/mongo/repository/ActionTrackingRepository.java
  src/main/java/peer/backend/mongo/repository/ActivityTrackingRepository.java
  src/main/java/peer/backend/repository/action/ActionTypeRepository.java
  src/main/java/peer/backend/repository/action/WalletRepository.java
  src/main/java/peer/backend/service/ExcelService.java
  src/main/java/peer/backend/service/action/ActionTypeService.java
  src/main/java/peer/backend/service/action/WalletService.java
Labels: refactor

#502 [FIX] tag list 권한 수정
  src/main/java/peer/backend/config/SecurityConfig.java
Labels: bug

#503 [FEATURE] 어드민 블랙리스트 관련 api 구현
  src/main/java/peer/backend/config/SecurityConfig.java
  src/main/java/peer/backend/config/jwt/ExceptionHandlerFilter.java
  src/main/java/peer/backend/config/jwt/JwtFilter.java
  src/main/java/peer/backend/controller/BlacklistController.java
  src/main/java/peer/backend/controller/ReportController.java
  src/main/java/peer/backend/converter/ReportProcessingStatusConverter.java
  src/main/java/peer/backend/dto/blacklist/AddBlacklistRequest.java
  src/main/java/peer/backend/dto/blacklist/BlacklistResponse.java
  src/main/java/peer/backend/dto/blacklist/HandleBlacklistRequest.java
  src/main/java/peer/backend/dto/report/ReportHandleRequest.java
  src/main/java/peer/backend/entity/blacklist/BlacklistHandleType.java
  src/main/java/peer/backend/entity/report/ReportHandleType.java
  src/main/java/peer/backend/oauth/OAuthAuthenticationSuccessHandler.java
  src/main/java/peer/backend/oauth/PrincipalOauth2UserService.java
  src/main/java/peer/backend/oauth/enums/LoginStatus.java
  src/main/java/peer/backend/repository/blacklist/BlacklistRepository.java
  src/main/java/peer/backend/service/LoginService.java
  src/main/java/peer/backend/service/blacklist/BlacklistService.java
Labels: enhancement

#510 [FEAT & REAFCTOR] 월렛 항목 API & 쿼리 최적화
  src/main/java/peer/backend/config/jwt/TokenProvider.java
  src/main/java/peer/backend/controller/ReportController.java
  src/main/java/peer/backend/controller/WalletController.java
  src/main/java/peer/backend/dto/wallet/CreateWalletItemRequest.java
  src/main/java/peer/backend/dto/wallet/UpdateWalletItemRequest.java
  src/main/java/peer/backend/dto/wallet/WalletItemResponse.java
  src/main/java/peer/backend/entity/action/ActionType.java
  src/main/java/peer/backend/entity/action/Wallet.java
  src/main/java/peer/backend/entity/user/enums/Role.java
  src/main/java/peer/backend/mongo/entity/enums/ActionTypeEnum.java
  src/main/java/peer/backend/repository/action/ActionTypeRepository.java
  src/main/java/peer/backend/repository/action/WalletRepository.java
  src/main/java/peer/backend/repository/user/UserRepository.java
  src/main/java/peer/backend/service/PrincipalDetailsService.java
  src/main/java/peer/backend/service/SessionService.java
  src/main/java/peer/backend/service/action/ActionTypeService.java
  src/main/java/peer/backend/service/action/WalletService.java
  src/main/java/peer/backend/service/report/ReportService.java
  src/test/java/peer/backend/config/jwt/TokenProviderTest.java
Labels: enhancement, refactor

#520 [FEATURE] 어드민 공지사항 API 개발
  src/main/java/peer/backend/annotation/ValidDateTime.java
  src/main/java/peer/backend/controller/NoticeController.java
  src/main/java/peer/backend/converter/NoticeStatusConverter.java
  src/main/java/peer/backend/converter/NotificationConverter.java
  src/main/java/peer/backend/dto/notice/CreateNoticeRequest.java
  src/main/java/peer/backend/dto/notice/NoticeIdRequest.java
  src/main/java/peer/backend/dto/notice/NoticeListResponse.java
  src/main/java/peer/backend/dto/notice/NoticeResponse.java
  src/main/java/peer/backend/dto/notice/UpdateNoticeRequest.java
  src/main/java/peer/backend/entity/notice/Notice.java
  src/main/java/peer/backend/entity/notice/NoticeStatus.java
  src/main/java/peer/backend/entity/notice/Notification.java
  src/main/java/peer/backend/repository/notice/NoticeRepository.java
  src/main/java/peer/backend/service/NoticeService.java
  src/main/java/peer/backend/service/file/ObjectService.java
  src/main/java/peer/backend/validator/DateTimeValidator.java
Labels: enhancement

#494 FIX : massage main service code critical points
  src/main/java/peer/backend/controller/message/MessaageController.java
  src/main/java/peer/backend/service/message/MessageMainService.java
  src/main/java/peer/backend/service/message/MessageSubService.java
Labels: enhancement

#495 FIX: socketio config
  src/main/java/peer/backend/config/SocketIoConfig.java
Labels: enhancement

#529 [FEATURE] 공지사항, 배너 게재 상태 변경 스케쥴링
  src/main/java/peer/backend/repository/banner/BannerRepository.java
  src/main/java/peer/backend/repository/notice/NoticeRepository.java
  src/main/java/peer/backend/scheduler/AdminScheduler.java
  src/main/java/peer/backend/scheduler/JobScheduler.java
  src/main/java/peer/backend/service/BannerService.java
  src/main/java/peer/backend/service/NoticeService.java
  src/main/java/peer/backend/service/UtilService.java
Labels: enhancement

#532 FIX: message bug
  src/main/java/peer/backend/controller/message/MessaageController.java
  src/main/java/peer/backend/dto/message/TargetForDelete.java
  src/main/java/peer/backend/repository/message/MessageIndexRepository.java
  src/main/java/peer/backend/service/message/MessageMainService.java
Labels: bug
