Repository peer-42seoul/Peer-Backend, pull requests merged in 2023-10, with the labels that each got.

#80 [FEATURE] 사용자 개인정보 조회 API, 비밀번호 변경 API
  backend/src/main/java/peer/backend/controller/profile/PersonalInfoController.java
  backend/src/main/java/peer/backend/dto/profile/PasswordRequest.java
  backend/src/main/java/peer/backend/dto/profile/PersonalInfoResponse.java
  backend/src/main/java/peer/backend/service/profile/PersonalInfoService.java
  backend/src/test/java/peer/backend/profile/PersonalInfoServiceTest.java
Labels: enhancement

#85 [FEATURE] 사용자 프로필 조회 API
  backend/src/main/java/peer/backend/controller/profile/ProfileController.java
  backend/src/main/java/peer/backend/dto/profile/EditProfileDTO.java
  backend/src/main/java/peer/backend/dto/profile/MyProfileResponse.java
  backend/src/main/java/peer/backend/dto/profile/UserLinkDTO.java
  backend/src/main/java/peer/backend/service/profile/ProfileService.java
  backend/src/test/java/peer/backend/service/profile/ProfileServiceTest.java
Labels: enhancement

#96 [FEATURE] make outline message service
  backend/src/main/java/peer/backend/BackendApplication.java
  backend/src/main/java/peer/backend/controller/message/MessaageController.java
  backend/src/main/java/peer/backend/controller/messageOld/MessageController.java
  backend/src/main/java/peer/backend/dto/asyncresult/AsyncResult.java
  backend/src/main/java/peer/backend/dto/message/LetterTargetDTO.java
  backend/src/main/java/peer/backend/dto/message/MsgContentDTO.java
  backend/src/main/java/peer/backend/dto/message/MsgDTO.java
  backend/src/main/java/peer/backend/dto/message/MsgObjectDTO.java
  backend/src/main/java/peer/backend/dto/message/SpecificMsgDTO.java
  backend/src/main/java/peer/backend/dto/message/SpecificScrollMsgDTO.java
  backend/src/main/java/peer/backend/dto/message/TargetDTO.java
  backend/src/main/java/peer/backend/dto/messageOld/MessageDTO.java
  backend/src/main/java/peer/backend/dto/messageOld/MessageSendRequest.java
  backend/src/main/java/peer/backend/dto/messageOld/MessageSendResponse.java
  backend/src/main/java/peer/backend/dto/messageOld/MessageUserDTO.java
  backend/src/main/java/peer/backend/entity/message/MessageIndex.java
  backend/src/main/java/peer/backend/entity/message/MessagePiece.java
  backend/src/main/java/peer/backend/entity/messageOld/Message.java
  backend/src/main/java/peer/backend/entity/messageOld/MessageType.java
  backend/src/main/java/peer/backend/entity/user/User.java
  backend/src/main/java/peer/backend/repository/message/MessageIndexRepository.java
  backend/src/main/java/peer/backend/repository/message/MessagePieceRepository.java
  backend/src/main/java/peer/backend/repository/messageOld/MessageRepository.java
  backend/src/main/java/peer/backend/service/message/MessageMainService.java
  backend/src/main/java/peer/backend/service/message/MessageSubService.java
  backend/src/main/java/peer/backend/service/messageOld/MessageServiceOld.java
  backend/src/test/java/peer/backend/repository/messageOld/MessageRepositoryTest.java
  backend/src/test/java/peer/backend/service/messageOld/MessageServiceTest.java
Labels: enhancement

#105 [FEATURE] 상대방 프로필(닉네임, 프로필 사진)확인 API, 링크 추가 API
  backend/src/main/java/peer/backend/controller/File/ProfileImageController.java
  backend/src/main/java/peer/backend/controller/profile/PersonalInfoController.java
  backend/src/main/java/peer/backend/controller/profile/ProfileController.java
  backend/src/main/java/peer/backend/dto/profile/request/EditProfileDTO.java
  backend/src/main/java/peer/backend/dto/profile/request/LinkListRequest.java
  backend/src/main/java/peer/backend/dto/profile/request/PasswordRequest.java
  backend/src/main/java/peer/backend/dto/profile/request/UserLinkDTO.java
  backend/src/main/java/peer/backend/dto/profile/response/MyProfileResponse.java
  backend/src/main/java/peer/backend/dto/profile/response/NicknameResponse.java
  backend/src/main/java/peer/backend/dto/profile/response/OtherProfileDto.java
  backend/src/main/java/peer/backend/dto/profile/response/OtherProfileImageUrlResponse.java
  backend/src/main/java/peer/backend/dto/profile/response/OtherProfileNicknameResponse.java
  backend/src/main/java/peer/backend/dto/profile/response/PersonalInfoResponse.java
  backend/src/main/java/peer/backend/dto/profile/response/UserImageResponse.java
  backend/src/main/java/peer/backend/dto/profile/response/YourProfileResponse.java
  backend/src/main/java/peer/backend/service/file/ProfileImageService.java
  backend/src/main/java/peer/backend/service/profile/PersonalInfoService.java
  backend/src/main/java/peer/backend/service/profile/ProfileService.java
  backend/src/test/java/peer/backend/File/ProfileImageServiceTest.java
  backend/src/test/java/peer/backend/profile/PersonalInfoServiceTest.java
  backend/src/test/java/peer/backend/profile/ProfileServiceTest.java
  backend/src/test/java/peer/backend/service/profile/ProfileServiceTest.java
Labels: enhancement

#101 [FEATURE] controller send back in specific letter
  backend/src/main/java/peer/backend/controller/message/MessaageController.java
  backend/src/main/java/peer/backend/dto/message/LetterTargetDTO.java
  backend/src/main/java/peer/backend/dto/message/Msg.java
  backend/src/main/java/peer/backend/dto/message/MsgListDTO.java
  backend/src/main/java/peer/backend/dto/message/MsgObjectDTO.java
  backend/src/main/java/peer/backend/dto/message/MsgOwner.java
  backend/src/main/java/peer/backend/dto/message/MsgTarget.java
  backend/src/main/java/peer/backend/dto/message/TargetDTO.java
  backend/src/main/java/peer/backend/service/message/MessageMainService.java
  backend/src/main/java/peer/backend/service/message/MessageSubService.java
Labels: enhancement

#90 [FEATURE] 유저 관련 추가 구현
  backend/src/main/java/peer/backend/config/SecurityConfig.java
  backend/src/main/java/peer/backend/controller/ExcelController.java
  backend/src/main/java/peer/backend/controller/MemberController.java
  backend/src/main/java/peer/backend/dto/security/UserInfo.java
  backend/src/main/java/peer/backend/entity/user/User.java
  backend/src/main/java/peer/backend/entity/user/enums/Role.java
  backend/src/main/java/peer/backend/oauth/PrincipalDetails.java
  backend/src/main/java/peer/backend/service/MemberService.java
  backend/src/test/java/peer/backend/keyword/UserPushKeywordRepositoryTest.java
  backend/src/test/java/peer/backend/team/InterestedProjectRepositoryTest.java
  backend/src/test/java/peer/backend/team/TeamUserRepositoryTest.java
Labels: enhancement

#110 [FIX] fix message send first
  backend/src/main/java/peer/backend/controller/message/MessaageController.java
  backend/src/main/java/peer/backend/dto/message/KeywordDTO.java
  backend/src/main/java/peer/backend/dto/message/MsgDTO.java
  backend/src/main/java/peer/backend/dto/message/MsgObjectDTO.java
  backend/src/main/java/peer/backend/repository/user/UserRepository.java
  backend/src/main/java/peer/backend/service/message/MessageMainService.java
  backend/src/main/java/peer/backend/service/message/MessageSubService.java
  backend/src/test/java/peer/backend/repository/messageOld/MessageRefactorTest.java
  backend/src/test/java/peer/backend/service/message/MessageServiceTest.java
Labels: bug

#104 [FEATURE] 키워드 알람 API 구현
  backend/src/main/java/peer/backend/controller/profile/KeywordAlarmController.java
  backend/src/main/java/peer/backend/dto/profile/KeywordRequest.java
  backend/src/main/java/peer/backend/dto/profile/KeywordResponse.java
  backend/src/main/java/peer/backend/entity/user/User.java
  backend/src/main/java/peer/backend/oauth/PrincipalDetails.java
  backend/src/main/java/peer/backend/service/profile/KeywordAlarmService.java
  backend/src/test/java/peer/backend/config/jwt/TokenProviderTest.java
  backend/src/test/java/peer/backend/profile/KeywordAlarmServiceTest.java
  backend/src/test/java/peer/backend/service/LoginServiceTest.java
Labels: enhancement

#119 [FIX] jpa message piece conversation
  backend/src/main/java/peer/backend/controller/message/MessaageController.java
  backend/src/main/java/peer/backend/entity/message/MessagePiece.java
  backend/src/main/java/peer/backend/service/message/MessageMainService.java
  backend/src/main/java/peer/backend/service/message/MessageSubService.java
Labels: bug

#120 [FIX] jpa realation with index
  backend/src/main/java/peer/backend/controller/message/MessaageController.java
  backend/src/main/java/peer/backend/entity/message/MessageIndex.java
  backend/src/main/java/peer/backend/entity/message/MessagePiece.java
  backend/src/main/java/peer/backend/repository/message/MessageIndexRepository.java
  backend/src/main/java/peer/backend/repository/message/MessagePieceRepository.java
  backend/src/main/java/peer/backend/service/message/MessageMainService.java
  backend/src/main/java/peer/backend/service/message/MessageSubService.java
Labels: bug

#121 [FIX] 2 issue
  backend/src/main/java/peer/backend/controller/message/MessaageController.java
  backend/src/main/java/peer/backend/dto/asyncresult/AsyncResult.java
  backend/src/main/java/peer/backend/entity/message/MessagePiece.java
  backend/src/main/java/peer/backend/service/message/MessageMainService.java
  backend/src/main/java/peer/backend/service/message/MessageSubService.java
Labels: bug

#123 [FIX] unread message number error fix
  backend/src/main/java/peer/backend/controller/message/MessaageController.java
  backend/src/main/java/peer/backend/service/message/MessageMainService.java
Labels: bug

#124 [FIX] infinite scroll
  backend/src/main/java/peer/backend/controller/message/MessaageController.java
  backend/src/main/java/peer/backend/dto/message/Msg.java
  backend/src/main/java/peer/backend/service/message/MessageMainService.java
  backend/src/main/java/peer/backend/service/message/MessageSubService.java
Labels: bug

#125 [FEATURE] Profile module - Favorite recruit API
  backend/src/main/java/peer/backend/controller/profile/FavoriteController.java
  backend/src/main/java/peer/backend/dto/profile/FavoritePage.java
  backend/src/main/java/peer/backend/dto/profile/response/FavoriteResponse.java
  backend/src/main/java/peer/backend/entity/user/User.java
  backend/src/main/java/peer/backend/service/profile/FavoriteService.java
  backend/src/test/java/peer/backend/profile/FavoriteControllerTest.java
  backend/src/test/java/peer/backend/profile/FavoriteServiceTest.java
Labels: enhancement

#115 [FEATURE] 프로필 수정 API, User 엔티티 수정
  backend/src/main/java/peer/backend/controller/messageOld/MessageController.java
  backend/src/main/java/peer/backend/controller/profile/ProfileController.java
  backend/src/main/java/peer/backend/dto/profile/request/EditProfileDTO.java
  backend/src/main/java/peer/backend/dto/profile/request/EditProfileRequest.java
  backend/src/main/java/peer/backend/dto/profile/request/LinkListRequest.java
  backend/src/main/java/peer/backend/dto/profile/request/UserLinkRequest.java
  backend/src/main/java/peer/backend/dto/profile/response/MyProfileResponse.java
  backend/src/main/java/peer/backend/dto/profile/response/OtherProfileResponse.java
  backend/src/main/java/peer/backend/dto/security/UserInfo.java
  backend/src/main/java/peer/backend/entity/user/User.java
  backend/src/main/java/peer/backend/oauth/PrincipalDetails.java
  backend/src/main/java/peer/backend/service/profile/ProfileService.java
  backend/src/main/resources/application.yml
  backend/src/test/java/peer/backend/File/ProfileImageServiceTest.java
  backend/src/test/java/peer/backend/config/jwt/TokenProviderTest.java
  backend/src/test/java/peer/backend/keyword/UserPushKeywordRepositoryTest.java
  backend/src/test/java/peer/backend/keyword/UserPushKeywordServiceTest.java
  backend/src/test/java/peer/backend/profile/ProfileServiceTest.java
  backend/src/test/java/peer/backend/profile/image/test1.png
  backend/src/test/java/peer/backend/profile/image/test2.png
  backend/src/test/java/peer/backend/repository/messageOld/MessageRefactorTest.java
  backend/src/test/java/peer/backend/service/LoginServiceTest.java
  backend/src/test/java/peer/backend/service/messageOld/MessageServiceTest.java
  backend/src/test/java/peer/backend/team/InterestedProjectRepositoryTest.java
  backend/src/test/java/peer/backend/team/InterestedServiceTest.java
  backend/src/test/java/peer/backend/team/TeamServiceTest.java
  backend/src/test/java/peer/backend/team/TeamUserRepositoryTest.java
Labels: enhancement

#127 [FIX] some issue fixed
  backend/src/main/java/peer/backend/controller/message/MessaageController.java
  backend/src/main/java/peer/backend/dto/message/KeywordDTO.java
  backend/src/main/java/peer/backend/exception/GlobalControllerAdvice.java
  backend/src/main/java/peer/backend/repository/message/MessageIndexRepository.java
  backend/src/main/java/peer/backend/repository/user/UserRepository.java
  backend/src/main/java/peer/backend/service/message/MessageMainService.java
  backend/src/main/java/peer/backend/service/message/MessageSubService.java
Labels: bug

#144 [FEATURE]: teamSetting - teamApplicants Api
  backend/src/main/java/peer/backend/controller/team/TeamController.java
  backend/src/main/java/peer/backend/dto/board/recruit/RecruitAnswerDto.java
  backend/src/main/java/peer/backend/repository/board/recruit/RecruitApplicantRepository.java
  backend/src/main/java/peer/backend/repository/user/UserRepository.java
  backend/src/main/java/peer/backend/service/team/TeamService.java
Labels: enhancement

#162 [REFACTOR]: TeamSetting Applicant's api
  backend/src/main/java/peer/backend/controller/team/TeamController.java
  backend/src/main/java/peer/backend/dto/team/TeamApplicantListDto.java
  backend/src/main/java/peer/backend/service/board/recruit/RecruitService.java
  backend/src/main/java/peer/backend/service/team/TeamService.java
  backend/src/test/java/peer/backend/team/TeamUserRepositoryTest.java
Labels: refactor

#173 feat: Implement API to fetch team information on team main page
  backend/src/main/java/peer/backend/controller/team/TeamController.java
  backend/src/main/java/peer/backend/dto/team/TeamInfoResponse.java
  backend/src/main/java/peer/backend/service/team/TeamService.java
Labels: enhancement

#176 [REAFCTOR] signup nickname return code 수정
  backend/src/main/java/peer/backend/controller/profile/ProfileController.java
Labels: refactor

#167 [REFACTOR] Signin refactoring
  backend/src/main/java/peer/backend/controller/SignInController.java
Labels: refactor

#168 [REFACTOR] 유저 탈퇴 관련 리팩토링
  backend/src/main/java/peer/backend/controller/SignUpController.java
  backend/src/main/java/peer/backend/service/MemberService.java
Labels: refactor

#183 [REFACTOR] tracking-excel endpoint modified
  backend/src/main/java/peer/backend/config/SecurityConfig.java
  backend/src/main/java/peer/backend/controller/ExcelController.java
Labels: refactor

#195 172 refactor all authentication keyword api
  backend/src/main/java/peer/backend/controller/profile/FavoriteController.java
  backend/src/main/java/peer/backend/controller/profile/KeywordAlarmController.java
  backend/src/main/java/peer/backend/controller/profile/PersonalInfoController.java
  backend/src/main/java/peer/backend/controller/profile/ProfileController.java
  backend/src/main/java/peer/backend/service/profile/FavoriteService.java
  backend/src/main/java/peer/backend/service/profile/KeywordAlarmService.java
  backend/src/main/java/peer/backend/service/profile/PersonalInfoService.java
  backend/src/main/java/peer/backend/service/profile/ProfileService.java
  backend/src/test/java/peer/backend/profile/FavoriteServiceTest.java
  backend/src/test/java/peer/backend/profile/KeywordAlarmServiceTest.java
  backend/src/test/java/peer/backend/profile/PersonalInfoServiceTest.java
  backend/src/test/java/peer/backend/profile/ProfileServiceTest.java
Labels: refactor

#193 refactor: profile api authentication
  backend/src/main/java/peer/backend/controller/profile/ProfileController.java
  backend/src/main/java/peer/backend/service/profile/ProfileService.java
  backend/src/test/java/peer/backend/profile/ProfileServiceTest.java
Labels: refactor

#202 152 refactor message hotfix authentification
  backend/src/main/java/peer/backend/controller/message/MessaageController.java
  backend/src/main/java/peer/backend/service/message/MessageMainService.java
Labels: integration

#201 feat: add teamUser entity job
  backend/src/main/java/peer/backend/entity/team/Team.java
  backend/src/main/java/peer/backend/entity/team/TeamUser.java
Labels: enhancement

#213 [FIX] when first social login - signup not tracking ft linking fix
  backend/src/main/java/peer/backend/entity/user/SocialLogin.java
  backend/src/main/java/peer/backend/oauth/OAuthAuthenticationSuccessHandler.java
  backend/src/main/java/peer/backend/oauth/PrincipalOauth2UserService.java
  backend/src/main/java/peer/backend/service/MemberService.java
  backend/src/main/java/peer/backend/service/SocialLoginService.java
  backend/src/main/java/peer/backend/service/UserService.java
  backend/src/main/resources/application-dev.yml
Labels: bug

#216 [FIX] add security setting for swagger
  backend/src/main/java/peer/backend/config/SecurityConfig.java
  backend/src/main/java/peer/backend/config/SwaggerConfig.java
  backend/src/main/java/peer/backend/controller/message/MessaageController.java
Labels: enhancement
