Repository peer-42seoul/Peer-Backend, pull requests merged in 2024-02, with the labels that each got.

#763 [REFACTOR] 공지사항, 배너, 신고 최신순으로 정렬
  src/main/java/peer/backend/controller/AnnouncementController.java
  src/main/java/peer/backend/repository/announcement/AnnouncementRepository.java
  src/main/java/peer/backend/repository/banner/BannerRepository.java
  src/main/java/peer/backend/repository/report/ReportRepository.java
  src/main/java/peer/backend/service/AnnouncementService.java
  src/main/java/peer/backend/service/BannerService.java
  src/main/java/peer/backend/service/report/ReportService.java
Labels: refactor

#765 REFACTOR: sign up logic for private info wrapping module
  src/main/java/peer/backend/service/PrivateInfoWrappingService.java
Labels: refactor

#775 [FEATURE] Oauth 실패 핸들링
  src/main/java/peer/backend/config/SecurityConfig.java
  src/main/java/peer/backend/oauth/OAuthAuthenticationFailureHandler.java
Labels: enhancement

#795 [FIX] 태그 삭제시 유저 스킬 삭제
  src/main/java/peer/backend/repository/user/UserSkillRepository.java
  src/main/java/peer/backend/service/TagService.java
Labels: bug

#824 [FIX] 태그 validation 수정
  src/main/java/peer/backend/dto/tag/CreateTagRequest.java
Labels: bug

#825 [FIX] 어드민 토큰이 일반 요청들을 방해하던 에러 수정
  src/main/java/peer/backend/config/jwt/JwtFilter.java
  src/main/java/peer/backend/config/jwt/TokenProvider.java
Labels: bug

#834 [REFACTOR] Request 로깅 수정
  src/main/java/peer/backend/aspect/RequestLoggingAspect.java
Labels: refactor

#854 [REFACTOR] 어드민 파트 짜잘 수정
  src/main/java/peer/backend/controller/object/ObjectController.java
  src/main/java/peer/backend/dto/announcement/AboutAnnouncementResponse.java
  src/main/java/peer/backend/dto/announcement/AnnouncementListResponse.java
  src/main/java/peer/backend/dto/announcement/AnnouncementResponse.java
  src/main/java/peer/backend/dto/announcement/CreateAnnouncementRequest.java
  src/main/java/peer/backend/dto/announcement/UpdateAnnouncementRequest.java
  src/main/java/peer/backend/entity/announcement/Announcement.java
  src/main/java/peer/backend/service/AnnouncementService.java
Labels: refactor

#858 Hotfix alarm list get api
  src/main/java/peer/backend/controller/noti/NotificationController.java
  src/main/java/peer/backend/repository/noti/NotificationTargetRepository.java
  src/main/java/peer/backend/service/noti/NotificationMainService.java
Labels: refactor
