Repository peer-42seoul/Peer-Backend, pull requests merged in 2024-01, with the labels that each got.

#530 [REFACTOR] 공지사항 & 배너 게재가 될 시 createdAt을 갱신하도록 리팩토링
  src/main/java/peer/backend/converter/NotificationConverter.java
  src/main/java/peer/backend/dto/notice/CreateNoticeRequest.java
  src/main/java/peer/backend/dto/notice/NoticeListResponse.java
  src/main/java/peer/backend/dto/notice/NoticeResponse.java
  src/main/java/peer/backend/entity/banner/Banner.java
  src/main/java/peer/backend/entity/notice/Notice.java
  src/main/java/peer/backend/entity/notice/NoticeNotification.java
  src/main/java/peer/backend/repository/notice/NoticeRepository.java
  src/main/java/peer/backend/scheduler/AdminScheduler.java
  src/main/java/peer/backend/service/NoticeService.java
Labels: refactor

#547 [FEATURE] 어드민 알림 파트 API 구현
  src/main/java/peer/backend/controller/AdminAlarmController.java
  src/main/java/peer/backend/converter/AlarmTargetTypeConverter.java
  src/main/java/peer/backend/dto/AlarmResponse.java
  src/main/java/peer/backend/dto/AlarmResponseContainable.java
  src/main/java/peer/backend/dto/admin/alarm/AlarmIdRequest.java
  src/main/java/peer/backend/dto/admin/alarm/AlarmListResponse.java
  src/main/java/peer/backend/dto/admin/alarm/SendAlarmRequest.java
  src/main/java/peer/backend/dto/admin/alarm/UpdateAlarmRequest.java
  src/main/java/peer/backend/dto/team/TeamDefaultResponse.java
  src/main/java/peer/backend/dto/user/UserDefaultResponse.java
  src/main/java/peer/backend/entity/AlarmTargetType.java
Labels: enhancement

#557 [FEATURE] 사용자 추적 파트 추가 개발
  src/main/java/peer/backend/annotation/tracking/BlacklistFreeTracking.java
  src/main/java/peer/backend/annotation/tracking/UserBanTracking.java
  src/main/java/peer/backend/annotation/tracking/UserReportTracking.java
  src/main/java/peer/backend/aspect/UserTrackingAspect.java
  src/main/java/peer/backend/mongo/repository/UserTrackingRepository.java
  src/main/java/peer/backend/service/blacklist/BlacklistService.java
  src/main/java/peer/backend/service/report/ReportService.java
Labels: enhancement

#562 [FEATURE] 팀 게시판 글쓰기 추적
  src/main/java/peer/backend/annotation/tracking/PostCreateTracking.java
  src/main/java/peer/backend/aspect/ActionTrackingAspect.java
  src/main/java/peer/backend/controller/board/BoardController.java
  src/main/java/peer/backend/controller/board/RecruitController.java
  src/main/java/peer/backend/mongo/entity/enums/ActionTypeEnum.java
  src/main/java/peer/backend/service/board/recruit/RecruitService.java
  src/main/java/peer/backend/service/board/team/BoardService.java
Labels: enhancement

#623 610 refactor myprofile skill tag modify
  src/main/java/peer/backend/controller/profile/ProfileController.java
  src/main/java/peer/backend/dto/profile/SkillDTO.java
  src/main/java/peer/backend/dto/profile/response/MyProfileResponse.java
  src/main/java/peer/backend/entity/tag/UserSkill.java
  src/main/java/peer/backend/entity/user/User.java
  src/main/java/peer/backend/repository/TagRepository.java
  src/main/java/peer/backend/repository/user/UserRepository.java
  src/main/java/peer/backend/repository/user/UserSkillsRepository.java
  src/main/java/peer/backend/service/profile/ProfileService.java
Labels: enhancement

#635 611 refactor myprofile myporfolio api
  src/main/java/peer/backend/controller/board/ShowcaseController.java
  src/main/java/peer/backend/controller/profile/ProfileController.java
  src/main/java/peer/backend/controller/team/TeamController.java
  src/main/java/peer/backend/dto/profile/response/PortfolioDTO.java
  src/main/java/peer/backend/entity/board/recruit/Recruit.java
  src/main/java/peer/backend/entity/board/team/Post.java
  src/main/java/peer/backend/entity/team/Team.java
  src/main/java/peer/backend/entity/user/User.java
  src/main/java/peer/backend/entity/user/UserPortfolio.java
  src/main/java/peer/backend/repository/board/recruit/RecruitTagRepository.java
  src/main/java/peer/backend/repository/user/UserPortfolioRepository.java
  src/main/java/peer/backend/service/board/recruit/RecruitService.java
  src/main/java/peer/backend/service/profile/UserPortfolioService.java
  src/main/java/peer/backend/service/team/TeamService.java
Labels: enhancement

#636 FEAT: remove duplicate checking from skill regist, request DTO change…
  src/main/java/peer/backend/controller/profile/ProfileController.java
  src/main/java/peer/backend/service/profile/ProfileService.java
Labels: enhancement

#651 [ REFACTOR] 태그 이름 중복 체크 로직 변경
  src/main/java/peer/backend/entity/tag/Tag.java
  src/main/java/peer/backend/service/TagService.java
Labels: refactor

#654 [FEAT] 어바웃 페이지 공지사항 API
  src/main/java/peer/backend/config/SecurityConfig.java
  src/main/java/peer/backend/controller/AnnouncementController.java
  src/main/java/peer/backend/dto/announcement/AboutAnnouncementListResponse.java
  src/main/java/peer/backend/dto/announcement/AboutAnnouncementResponse.java
  src/main/java/peer/backend/repository/announcement/AnnouncementRepository.java
  src/main/java/peer/backend/service/AnnouncementService.java
Labels: enhancement

#659 [FEAT] private info sealing feature 3
  src/main/java/peer/backend/controller/PrivateInfoWrappingController.java
  src/main/java/peer/backend/dto/privateinfo/MainSeedDTO.java
  src/main/java/peer/backend/dto/privateinfo/PrivateDataDTO.java
  src/main/java/peer/backend/service/PrivateInfoWrappingService.java
Labels: enhancement

#660 [FEAT] private info sealing feature 4
  src/main/java/peer/backend/controller/PrivateInfoWrappingController.java
  src/main/java/peer/backend/dto/profile/request/ChangePasswordRequest.java
  src/main/java/peer/backend/dto/profile/request/PasswordRequest.java
  src/main/java/peer/backend/dto/security/UserInfo.java
  src/main/java/peer/backend/service/PrivateInfoWrappingService.java
Labels: enhancement

#661 [FEAT] private info sealing feature 5
  src/main/java/peer/backend/dto/privateinfo/enums/PrivateActions.java
  src/main/java/peer/backend/dto/profile/request/ChangePasswordRequest.java
  src/main/java/peer/backend/dto/profile/request/PasswordRequest.java
  src/main/java/peer/backend/dto/security/UserInfo.java
  src/main/java/peer/backend/service/PrivateInfoWrappingService.java
Labels: enhancement

#657 [REFACTOR] 팀 설정 페이지 짜잘 수정
  src/main/java/peer/backend/controller/team/TeamController.java
  src/main/java/peer/backend/dto/team/TeamSettingInfoDto.java
  src/main/java/peer/backend/entity/team/Team.java
  src/main/java/peer/backend/service/team/TeamService.java
Labels: refactor

#717 FIX: code long value into string
  src/main/java/peer/backend/controller/PrivateInfoWrappingController.java
  src/main/java/peer/backend/dto/privateinfo/InitSecretDTO.java
  src/main/java/peer/backend/dto/privateinfo/InitTokenDTO.java
  src/main/java/peer/backend/dto/privateinfo/MainSeedDTO.java
  src/main/java/peer/backend/dto/privateinfo/PrivateDataDTO.java
  src/main/java/peer/backend/service/PrivateInfoWrappingService.java
Labels: bug, enhancement

#720 hot fix
  src/main/java/peer/backend/controller/dnd/DnDSubController.java
Labels: enhancement

#715 [FEATURE] 사용자 추적 모듈 추가 개발
  src/main/java/peer/backend/annotation/tracking/CompleteTeamTracking.java
  src/main/java/peer/backend/annotation/tracking/DisperseTeamTracking.java
  src/main/java/peer/backend/aspect/TeamTrackingAspect.java
  src/main/java/peer/backend/controller/team/TeamController.java
  src/main/java/peer/backend/service/team/TeamService.java
Labels: enhancement

#725 724 hotfix dnd sub module hotfix
  src/main/java/peer/backend/config/RedisRepositoryConfig.java
  src/main/java/peer/backend/controller/dnd/DnDSubController.java
  src/main/java/peer/backend/dto/dndSub/TeamIdentifierDTO.java
  src/main/java/peer/backend/service/dnd/DnDSubService.java
Labels: bug

#727 FEAT: wrapped signIn api to privateInfoWrapping module
  src/main/java/peer/backend/controller/PrivateInfoWrappingController.java
  src/main/java/peer/backend/controller/SignInController.java
  src/main/java/peer/backend/dto/privateinfo/enums/PrivateActions.java
  src/main/java/peer/backend/service/PrivateInfoWrappingService.java
Labels: enhancement

#750 747 feat external page message api
  src/main/java/peer/backend/controller/message/MessaageController.java
  src/main/java/peer/backend/controller/socket/SocketIoServerController.java
  src/main/java/peer/backend/dto/message/MsgContentDTO.java
  src/main/java/peer/backend/repository/message/MessageIndexRepository.java
  src/main/java/peer/backend/service/message/MessageMainService.java
Labels: enhancement
